services:
  auth-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    volumes:  
      - sql_data_auth_server:/var/opt/mssql

  auth-server:
    build:
      context: .
      dockerfile: AuthProvider.Dockerfile
    ports:
      - "7082:8080"
    environment:
      - ConnectionStrings__AuthProviderDbContextConnection=Server=auth-server-db;Database=AuthProvider;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True
      - OpenIddictServer__Authority=http://localhost:7082
      - OpenIddictServer__Clients__MvcClient__RedirectUri=http://localhost:7197/callback/login/local
      - OpenIddictServer__Clients__MvcClient__PostLogoutRedirectUri=http://localhost:7197/callback/logout/local
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - auth-server-db
    volumes:
      - dp-keys:/root/.aspnet/DataProtection-Keys
    extra_hosts:
      - "localhost:host-gateway"

  resource-server:
    build:
      context: .
      dockerfile: AuthProvider.ResourceServer.Dockerfile
    ports:
      - "7240:8080"
    environment:
      - OpenIddictValidation__Authority=http://localhost:7082
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - auth-server
    volumes:
      - dp-keys:/root/.aspnet/DataProtection-Keys
    extra_hosts:
      - "localhost:host-gateway"

  client:
    build:
      context: .
      dockerfile: AuthProvider.Client.Dockerfile
    ports:
      - "7197:8080"
    environment:
      - OpenIddictClient__Authority=http://localhost:7082
      - OpenIddictClient__ClientSecret=65bd1ee0-8d7c-4600-bb01-10f633ac1c8d
      - OpenIddictClient__ClientId=mvc-client
      - ResourceServer__BaseUri=http://localhost:7240
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - auth-server
    volumes:
      - dp-keys:/root/.aspnet/DataProtection-Keys
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  sql_data_auth_server:
  sql_data_client:
  dp-keys: