@startuml name "Sequence_OIDC"
title "OpenID Connect Authorization Code Flow для клієнт-серверного додатку"

actor "Користувач" as User
participant "Користувацький\nагент" as UserAgent
participant "Клієнт" as Client
participant "Сервер авторизації" as OP

autonumber

== 1. Ініціація та підготовка запиту ==
User -> UserAgent: Ініціює логін
UserAgent -> Client: Запит на логін
Client -> Client: Генерація code_verifier\nта code_challenge
Client -> OP: Запит на /connect/authorize\nз code_challenge
activate OP
OP --> UserAgent: Редирект на сторінку\nавтентифікації (302)
deactivate OP

== 2. Автентифікація користувача ==
UserAgent -> OP: Перехід на сторінку логіну
OP --> UserAgent: Показ сторінки автентифікації
User -> UserAgent: Заповнення\nоблікових даних
UserAgent -> OP: Надсилання облікових даних
activate OP
OP -> OP: Обробка облікових даних,\nстворення сесії
OP -> UserAgent: Встановлення session cookie,\n редирект назад на /connect/authorize
deactivate OP

== 3. Отримання коду авторизації ==
UserAgent -> OP: Слідування редиректу, \nз переходом на /connect/authorize (with cookie)
activate OP
OP -> OP: Перевірка сесії\nавтентифікації

opt Потреба в отриманні явної згоди (Consent)
    OP --> UserAgent: Запит на надання дозволів (Scopes)
    UserAgent --> User: Показ вікна згоди
    User -> UserAgent: Підтвердження згоди
    UserAgent -> OP: Надсилання підтвердження
end

OP --> UserAgent: Редирект на клієнт\nз кодом авторизації (302)
deactivate OP
UserAgent --> Client: Передача коду\nавторизації\nза Redirect URI

== 4. Обмін коду на токени ==
Client -> OP: Запит на токен до /connect/token\nз кодом авторизації\nта code_verifier
activate OP
OP -> OP: Валідація коду,\ncode_verifier та code_challenge,\nгенерація токенів
OP --> Client: access_token + id_token\n+ refresh_token
deactivate OP

@enduml