@startuml "Identity UI Layer Class Diagram"
title "Діаграма класів шару Identity UI"

skinparam linetype ortho
skinparam classAttributeIconSize 0

' --- Identity Pages ---
class PageModel <<framework>>


' --- Login Model ---
class LoginModel {
    +Input: LoginInputModel
    +ErrorMessage: string?
    +ReturnUrl: string?
    - _signInManager: SignInManager<ApplicationUser> {readOnly}

    +OnGet(string?): IActionResult
    +OnPostAsync(string?): Task<IActionResult>
}

class LoginInputModel {
    +Email: string
    +Password: string
    +RememberMe: bool
}

LoginModel +-up- LoginInputModel
PageModel <|-left- LoginModel

' --- Logout Model ---'
class LogoutModel {
    +PostLogoutRedirectUri: string?
    +ClientId: string?
    +IdTokenHint: string?
    +State: string?
    - _signInManager: SignInManager<ApplicationUser> {readOnly}

    +OnPostAsync(): Task<IActionResult>
}

PageModel <|-up- LogoutModel



' --- Register Model ---
class RegisterModel {
    - _signInManager: SignInManager<ApplicationUser> {readOnly}
    - _userManager: UserManager<ApplicationUser> {readOnly}
    - _userStore: IUserStore<ApplicationUser> {readOnly}

    +Input: RegisterInputModel
    +ReturnUrl: string?

    +OnGet(string?): IActionResult
    +OnPostAsync(string?): Task<IActionResult>
    -GetEmailStore(): IUserEmailStore<ApplicationUser>
}

class RegisterInputModel {
    +Email: string
    +Password: string
    +ConfirmPassword: string
}

RegisterModel +-left- RegisterInputModel
PageModel <|-- RegisterModel

' --- Index Model ---
class IndexModel {
    - _userManager: UserManager<ApplicationUser> {readOnly}
    - _signInManager: SignInManager<ApplicationUser> {readOnly}

    +Input: IndexInputModel
    +Username: string
    +StatusMessage: string?
    +OnGetAsync(): Task<IActionResult>
    +OnPostAsync(): Task<IActionResult>
    -LoadAsync(ApplicationUser): Task
}

class IndexInputModel {
    +PhoneNumber: string?
}

IndexModel +-- IndexInputModel
PageModel <|-right- IndexModel

@enduml